import apiSlice from "./api-slice";

const FooterApi = apiSlice.injectEndpoints({
    endpoints: (builder) => ({
        serviceDetails: builder.query({
            query: (uid) => ({
                url: `/service-details-page/${uid}`,
                method: "GET",
            }),
            providesTags: [], // Specify tags if you plan to invalidate this cache or leave empty
        }),
    }),
    overrideExisting: false,
});

// Exporting the hook generated by the query
export const { useServiceDetailsQuery } = FooterApi;
